### ISSUE TITLE
Freegeoip adress looks invalid

### ISSUE THREAD

**Issue by GUNT0815** [shizunge/endlessh-go#38]
func geohashAndLocationFromFreegeoip(address string) (string, string, string, error) {
	var geo freegeoip
	response, err := http.Get("https://freegeoip.live/json/" + address)

As mentioned here https://freegeoip.io/ the api call should be different: freegeoip.io/{format}/{IP_or_hostname}.

**Comment by shizunge** [comment]
Freegeoip.live seemed no longer available.
I am not sure freegeoio.io and freegeoip.live are same. I will take a look later.
This should not be a blocking issue, as there are alternatives.

**Comment by shizunge** [comment]
I have problem get result from https://freegeoip.io/ . I alwaye get 404.

I think I will remove freegeoip as a provider.
