### ISSUE TITLE
ho wto use options ?

### ISSUE THREAD

**Issue by ErfanDL** [shizunge/endlessh-go#4]
Hi. how can I use ./endlessh-go options ?
for example how to use -geoip_supplier option ?

thanks.

**Comment by shizunge** [comment]
They are command line arguments, e.g.
`./endlessh-go -geoip_supplier=ip-api`

If you are using docker, see the examples folder.

**Comment by ErfanDL** [comment]
> They are command line arguments, e.g. `./endlessh-go -geoip_supplier=ip-api`
> 
> If you are using docker, see the examples folder.

thanks for reply. it's working from CLI and logs saved to prometheus metrics file. but there is no data in grafana dashboard.

![Screenshot 2022-01-21 120937](https://user-images.githubusercontent.com/14868771/150494576-4238ec28-5407-40b8-843b-c5d7dc3e3b79.jpg)

![Screenshot 2022-01-21 121010](https://user-images.githubusercontent.com/14868771/150495337-7f470cae-f721-4e43-a313-adf1448eb20e.jpg)

![Screenshot 2022-01-21 121032](https://user-images.githubusercontent.com/14868771/150495369-ef451904-dbfa-44ba-b216-e35c682cf1a9.jpg)

**Comment by shizunge** [comment]
There are 4 independent queries
* Sent Bytes
* Unique IPs
* Current Connections
* Clients

You did not get any of them, I would suspect the data source was not selected correctly.

**Comment by shizunge** [comment]
@ErfanDL do you still have problems? Or I will close this bug.

**Comment by ErfanDL** [comment]
> @ErfanDL do you still have problems? Or I will close this bug.
for now I run the docker version (example). I can't configure the prometheus configuration to work.
thanks.

**Comment by shizunge** [comment]
I tested the example locally again, and it seems working.

In your screenshot in the [commnet above ](https://github.com/shizunge/endlessh-go/issues/4#issuecomment-1018299204), no one connects to the endlessh-go. So nothing to display on the dashboard. e.g. this one *endlessh_client_open_count_total 0*

If you want to see some data on the dashboard, open a terminal and and run `ssh -p 2222 localhost`, assuming you are running the example and endlessh-go port bound to port 2222 on localhost. A few minutes later, you could see a client with IP in a private IP range, and country is Unknown.

Also, please run `docker-compose pull` before `docker-compose up -d` to get the latest images of the containers.

I am not closing this bug, as there seems no problem with endlessh-go or the example.

**Comment by ErfanDL** [comment]
> I tested the example locally again, and it seems working.
> 
> In your screenshot in the [commnet above ](https://github.com/shizunge/endlessh-go/issues/4#issuecomment-1018299204), no one connects to the endlessh-go. So nothing to display on the dashboard. e.g. this one _endlessh_client_open_count_total 0_
> 
> If you want to see some data on the dashboard, open a terminal and and run `ssh -p 2222 localhost`, assuming you are running the example and endlessh-go port bound to port 2222 on localhost. A few minutes later, you could see a client with IP in a private IP range, and country is Unknown.
> 
> Also, please run `docker-compose pull` before `docker-compose up -d` to get the latest images of the containers.
> 
> I am going to close this bug, as there seems no problem with endlessh-go or the example.

just a question. What should I enter in these fields? ( job and host )
![Screenshot 2022-02-12 122614](https://user-images.githubusercontent.com/14868771/153704656-66e1fa4a-4825-4ba8-84d3-5eca9195ab2f.png)

**Comment by ErfanDL** [comment]
the problem solved by reconfiguring the prometheus.

![Uploading Screenshot 2022-02-13 121823.png…]()

**Comment by ErfanDL** [comment]
the problem solved by reconfiguring the prometheus.

![Screenshot 2022-02-13 121823](https://user-images.githubusercontent.com/14868771/153745991-4d9e6218-8d29-4b88-b577-0fdf88b6bdc5.jpg)
