### ISSUE TITLE
no connection to the consol

### ISSUE THREAD

**Issue by luckyheiko** [shizunge/endlessh-go#41]
i get every time the fault
![1](https://user-images.githubusercontent.com/26415601/209185117-167947f2-2475-418f-952c-f9c8ebe22119.png)

is this a fault on my side?
if yes, how can i fix the problem?

**Comment by shizunge** [comment]
That is because the docker image is based on gcr.io/distroless/base, which does not contain "sh"

**Comment by luckyheiko** [comment]
Thank you for the information
