### ISSUE TITLE
Some metrics missing

### ISSUE THREAD

**Issue by Yoshimanly** [shizunge/endlessh-go#6]
Hi, some metrics are missing from grafana dashboard.

Grafana 8.3.4
Docker: '-logtostderr' '-v=1' '-enable_prometheus' '-geoip_supplier=freegeoip' - Can confirm that IP's, country and trap times metrics are getting to prometheus:2112/metrics (image below).

![image](https://user-images.githubusercontent.com/37461591/152658398-df58d4e6-8f6e-45dc-bc19-9213cc3b9641.png)

![image](https://user-images.githubusercontent.com/37461591/152658528-3338cfbb-465c-475d-a39e-ca521cc442c6.png)

**Comment by shizunge** [comment]
Which version Grafana and dashboard are you using?

There is a problem with old dashboard and Grafana 8.3.4. I fixed it about 10 days ago.

Could you try the latest dashboard.

**Comment by Yoshimanly** [comment]
Grafana v8.3.4 (a551d74b1), I downloaded this package grafana-enterprise_8.3.4_amd64.deb from their website.

So, should I update to 8.4.0 beta?

**Comment by shizunge** [comment]
Have you try the latest dashboard?
I.e. from this repo or by from https://grafana.com/grafana/dashboards/15156/revisions

**Comment by Yoshimanly** [comment]
Yes, I've discovered that the problem is the latest (v5), I installed the (v4) and it's working fine now

![image](https://user-images.githubusercontent.com/37461591/152692723-5ad5eb08-eebe-4ef3-bfac-5b2a9dc181ab.png)

**Comment by shizunge** [comment]
En....
I tried importing version 5 again. It displays correctly on my side.

**Comment by shizunge** [comment]
It does not use any LOKI data source. When you import the dashboard, Grafana should ask you to select a Prometheus data source.

**Comment by Yoshimanly** [comment]
This is the error I get when I import version 5

It is trying to get something from loki. Probably you have loki running to and it's getting metrics from there

parse error at line 1, col 2: syntax error: unexpected IDENTIFIER
[Object]()
[status:400]()
[statusText:""]()
[data:Object]()
[message:"parse error at line 1, col 2: syntax error: unexpected IDENTIFIER"]()
[error:""]()
[response:"parse error at line 1, col 2: syntax error: unexpected IDENTIFIER"]()
[config:Object]()
[headers:Object]()
[url:"api/datasources/proxy/2/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=(endlessh_client_trapped_time_seconds%7Binstance%3D%22192.168.1.24%3A2112%22%2Cjob%3D%22endlessh%22%7D%20-%20endlessh_client_trapped_time_seconds%7Binstance%3D%22192.168.1.24%3A2112%22%2Cjob%3D%22endlessh%22%7D%20offset%201m)%20%3E%200%20or%20(endlessh_client_trapped_time_seconds%7Binstance%3D%22192.168.1.24%3A2112%22%2Cjob%3D%22endlessh%22%7D!%3D0%20unless%20endlessh_client_trapped_time_seconds%7Binstance%3D%22192.168.1.24%3A2112%22%2Cjob%3D%22endlessh%22%7D%20offset%201m)&start=1644109445932000000&end=1644195845932000000&step=60"]()
[retry:0]()
[hideFromInspector:false]()
[message:"parse error at line 1, col 2: syntax error: unexpected IDENTIFIER"]()

**Comment by shizunge** [comment]
To be frank, I have no idea where this error coming from.
I do not run Loki on my side.
And there is no "IDENTIFIER" in the dashboard json file.

**Comment by Yoshimanly** [comment]
Weird, why does the v4 work then?

**Comment by shizunge** [comment]
One way to debug this, is to export the dashboard which has the problem to a json file.
Then diff it with the json file downloaded from Grafana and/or github.

**Comment by Yoshimanly** [comment]
I been trying, but I'm not skilled enough. I'm going to run the v4, everything works fine.

Should I close the issue?

Anyhow, thank you so much for making this dashboard and this version of endlessh available, you are awesome

**Comment by shizunge** [comment]
Some entries are missing in the "clients table" (bottom right) in v4. All other panels (e.g. total connections, total time, global maps etc.) should be fine.

If you think you found a solution, you can close the bug, due to I cannot reproduce it.

**Comment by Yoshimanly** [comment]
It's probably my grafana instalation.

Thank you for your help, and this project

**Comment by Yoshimanly** [comment]
I've discovered the problem. Prometheus has to have the default flag (as seen below) for your dashboard to work. If none of the datasources is default, it will not throw errors and just say "NO DATA" if loki or any other datasource is default, it will throw the error that I pasted above.

Seems to be that your dashboard is looking for a default datasource and no prometheus itself

![image](https://user-images.githubusercontent.com/37461591/153004246-5e03a1e6-ea11-4792-b51a-071cfd730917.png)

**Comment by shizunge** [comment]
Thank you for debugging! I will take a look.

**Comment by shizunge** [comment]
If you had time, could you try the latest version?
Thanks,

**Comment by Yoshimanly** [comment]
It works perfectly, and it loads a lot faster. 

Thank you for fixing it!

I'll go ahead a close this issue
