### ISSUE TITLE
Unable to find Geolite2-Country.mmdb

### ISSUE THREAD

**Issue by Le-Kat** [shizunge/endlessh-go#69]
Endlessh-go reports country, location, and geohash data as unknown; after looking at the systemd page, I see this error message: `Failed to obatin the geohash of [ipv4 redacted]: open /GeoLite2-Country.mmdb: no such file or directory.`

when running `ls -lh /GeoLite2-Country.mmdb` I get: `-rw-r--r-- 1 root root 6.2M Mar  5 13:41 /GeoLite2-Country.mmdb`, however even after running `chmod 777 /GeoLite2-Country.mmdb` I still get the same error. I'm running in bare metal (not docker) so there *shouldn't be* anything preventing it from accessing the database file. Does it need to be owned by a specific user? Does it need to be in a specific directory/have a specific name?

If it helps with debugging, I'm running this on nixOS 22.11.3810.3d302c67ab8 (due to using nixos & endlessh-go not having a --version flag, I can only say that I'm running the latest version as of 2023/08/23). I have my service configuration as follows:
```nixos
services.endlessh-go = {
	
	enable = true;
	port = 22;
	openFirewall = true;
	extraOptions = [
		"-enable_prometheus"
		"-prometheus_entry ''"
		"-geoip_supplier 'max-mind-db'"
		"-max_mind_db '/GeoLite2-Country.mmdb"
	];
	prometheus = {
		
		enable = false;
		listenAddress = "127.0.0.1";
		port = 2112;
	};
};
```

**Comment by Le-Kat** [comment]
It seems to be a permission issue, it works fine when running as root user (by invoking the binary manually). I don't know why it can't access the file even with 777 permission though.

**Comment by Le-Kat** [comment]
It turns out that endlessh-go's systemd service prohibits it from accessing the main file system.

Closing this issue since it lies with how nixOS handles systemd services, not with endlessh-go itself.

**Comment by martijnboers** [comment]
@Le-Kat do you mind sharing how you resolved this issue?

**Comment by Le-Kat** [comment]
It's been a few months, but my nixos config is as follows:

```nix
	services.endlessh-go = {
		
		enable = true;
		port = 22;
		openFirewall = false;
		extraOptions = [
			
			"-geoip_supplier 'max-mind-db'"
			"-max_mind_db '/var/db/maxmind/GeoLite2-Country.mmdb'"
		];
		prometheus = {
			
			enable = true;
			port = 2112;
		};
	};
	
	systemd.services = {
		endlessh-go = {
			serviceConfig.BindPaths = "/var/db/maxmind/GeoLite2-Country.mmdb";
		};
	};
```

I presume it's the `systemd.services.endlessh-go.serviceConfig.BindPaths` that allowed endlessh-go to access the db file.
