### ISSUE TITLE
docker-compose example missing

### ISSUE THREAD

**Issue by sunjam** [shizunge/endlessh-go#78]
https://github.com/shizunge/endlessh-go/tree/main/examples

**Comment by shizunge** [comment]
Could you be more specified?
There are two examples:
* https://github.com/shizunge/endlessh-go/tree/main/examples/docker-maxmind
* https://github.com/shizunge/endlessh-go/tree/main/examples/docker-simple

**Comment by shizunge** [comment]
Add links to examples
