### ISSUE TITLE
Docker fails to pull image from GitHub

### ISSUE THREAD

**Issue by CorySanin** [shizunge/endlessh-go#83]
```
$> docker --version
Docker version 24.0.7, build afdd53b4e3
$> sudo docker pull ghcr.io/shizunge/endlessh-go:latest
latest: Pulling from shizunge/endlessh-go
manifest unknown
```

Pulling from Docker Hub works fine.

**Comment by shizunge** [comment]
Cannot reproduce on my machine (x86).

Which arch is your machine?

**Comment by CorySanin** [comment]
x86_64

Tried on Ubuntu 22.04.3 and Artix.

**Comment by shizunge** [comment]
Related topic https://github.com/orgs/community/discussions/45779

`docker manifest inspect ghcr.io/shizunge/endlessh-go` failed. got "manifest unknown"

` docker buildx imagetools inspect ghcr.io/shizunge/endlessh-go` succeeded.

**Comment by CorySanin** [comment]
Hmm interesting. This happened to be the first ghcr image I've had this issue with. Closing as it's clearly GitHub's issue 🙂

**Comment by shizunge** [comment]
`docker manifest inspect ghcr.io/shizunge/endlessh-go` seems working on the latest one now.

We need to keep an eye on it, because I remember I can pull the previous latest image from ghcr.io before. Then we meet this unknown manifest problem.

**Comment by shizunge** [comment]
I may find a reason why images from ghcr.io become unavailable. 

I have a workflow to delete untagged images. These images is actually the release images for different OS/Arch.

I will keep untagged image for now.
