### ISSUE TITLE
Usage of glog flags

### ISSUE THREAD

**Issue by FoxxMD** [shizunge/endlessh-go#84]
I see that endlessh-go is using [glog](https://github.com/google/glog) for logging along with `gflags` (I think?) to pass options as args. Some of endlessh-go's args are pulled directly from [`logging.cc`](https://github.com/google/glog/blob/master/src/logging.cc#L124) but when I try to use flags not listed, `timestamp_in_logfile_name` and `max_log_size`, I get an error. 

```
flag provided but not defined: -max_log_size
Usage of /endlessh 
  -alsologtostderr
...
```

I don't see where in endlessh-go's code where the [logging flags are defined...](https://github.com/shizunge/endlessh-go/blob/main/main.go#L107) Would it be possible to use these additional flags? I'm try to configure basic log rotation. Thanks!

**Comment by shizunge** [comment]
`./endlessh-go --help` should list all the flags

We use https://github.com/golang/glog, not https://github.com/google/glog, the later one is for c++.
